#!/usr/bin/env python3
"""
Experiment A: Tunnel Latency Analysis

Reads per-sample CSV files from ~/exp_data/A/ and produces:
  1. Console table: P50 / P99 / P99.9 for each (protocol × message-size)
  2. summary.csv  — machine-readable, for LaTeX table generation
  3. latency_cdf.png — optional CDF plot (requires matplotlib)

CSV file naming convention (generated by bench_host):
  comch_64B.csv, comch_256B.csv, ..., comch_65536B.csv
  tcp_64B.csv,   tcp_256B.csv,   ..., tcp_65536B.csv

Each CSV has a single column: latency_ns
"""

import os
import sys
import glob
import numpy as np

DATA_DIR  = os.path.expanduser("~/exp_data/A")
SIZES     = [64, 256, 1024, 4096, 65536]
PROTOCOLS = ["comch", "tcp"]


def load_samples_us(path: str) -> np.ndarray:
    """Load latency values from CSV and convert ns → µs."""
    with open(path) as f:
        lines = f.readlines()
    values = []
    for line in lines:
        line = line.strip()
        if not line or line.lower().startswith("latency"):
            continue
        try:
            values.append(float(line))
        except ValueError:
            pass
    return np.array(values, dtype=np.float64) / 1000.0   # ns → µs


def analyze() -> list[dict]:
    results = []
    for proto in PROTOCOLS:
        for size in SIZES:
            pattern = os.path.join(DATA_DIR, f"{proto}_{size}B.csv")
            matches = glob.glob(pattern)
            if not matches:
                print(f"  [WARN] missing: {pattern}", file=sys.stderr)
                continue
            samples = load_samples_us(matches[0])
            if len(samples) == 0:
                print(f"  [WARN] empty file: {matches[0]}", file=sys.stderr)
                continue
            results.append({
                "protocol" : proto.upper(),
                "size_B"   : size,
                "n"        : len(samples),
                "avg_us"   : float(np.mean(samples)),
                "p50_us"   : float(np.percentile(samples, 50)),
                "p99_us"   : float(np.percentile(samples, 99)),
                "p999_us"  : float(np.percentile(samples, 99.9)),
                "max_us"   : float(np.max(samples)),
            })
    return results


def print_table(results: list[dict]) -> None:
    hdr = f"{'Protocol':<10} {'Size':>8} {'n':>7} {'Avg µs':>8} " \
          f"{'P50 µs':>8} {'P99 µs':>8} {'P99.9 µs':>10} {'Max µs':>8}"
    print("\n=== Experiment A: Tunnel Latency ===")
    print(hdr)
    print("-" * len(hdr))
    for r in results:
        print(f"{r['protocol']:<10} {r['size_B']:>8} {r['n']:>7} "
              f"{r['avg_us']:>8.3f} {r['p50_us']:>8.3f} "
              f"{r['p99_us']:>8.3f} {r['p999_us']:>10.3f} {r['max_us']:>8.3f}")


def save_csv(results: list[dict]) -> None:
    out = os.path.join(DATA_DIR, "summary.csv")
    import csv
    fields = ["protocol", "size_B", "n", "avg_us", "p50_us", "p99_us", "p999_us", "max_us"]
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(results)
    print(f"\nSummary saved → {out}")


def try_plot(results: list[dict]) -> None:
    """Optional: CDF plot for 1KB messages (most representative for control plane)."""
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed; skipping plot. (pip3 install matplotlib)")
        return

    fig, ax = plt.subplots(figsize=(6, 4))
    target_size = 1024
    colors = {"COMCH": "#2196F3", "TCP": "#F44336"}

    for proto in PROTOCOLS:
        path = os.path.join(DATA_DIR, f"{proto}_{target_size}B.csv")
        if not os.path.exists(path):
            continue
        samples = np.sort(load_samples_us(path))
        cdf = np.arange(1, len(samples) + 1) / len(samples)
        ax.plot(samples, cdf, label=proto.upper(),
                color=colors.get(proto.upper(), "gray"), linewidth=1.5)

    ax.set_xlabel("One-way latency (µs)")
    ax.set_ylabel("CDF")
    ax.set_title(f"Latency CDF — {target_size}B messages")
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.set_xlim(left=0)
    ax.set_ylim(0, 1)

    out = os.path.join(DATA_DIR, "latency_cdf.png")
    fig.savefig(out, dpi=150, bbox_inches="tight")
    print(f"CDF plot saved → {out}")
    plt.close(fig)


if __name__ == "__main__":
    os.makedirs(DATA_DIR, exist_ok=True)
    results = analyze()
    if not results:
        print("No data found. Run exp_A_latency.sh first.")
        sys.exit(1)
    print_table(results)
    save_csv(results)
    try_plot(results)
